### PR TITLE
Allow copying to the clipboard on macOS

### PR DESCRIPTION
**Pull request by RobertAudi**
Clipboard support on macOS has been added in Aloxaf/silicon#33

### CODE REVIEW

**Comment by segeljakt** [comment]
Awesome, thank you. I'm on my phone but I will merge this when I'm at my PC

**Comment by RobertAudi** [comment]
@segeljakt I think that the feature doesn't work as advertised 🤦‍♂ I just tested it, and while it doesn't throw an error, it fills the clipboard with an empty string.

So unless this problem only happens to me I think I better close this PR until the thing actually works...

**Comment by segeljakt** [comment]
Hmm strange, thanks for reporting

**Comment by segeljakt** [comment]
If you run:
```
echo "ab" | silicon --to-clipboard --language python
```
Do you get an error message?

I'm getting `[error] This feature hasn't been implemented for your system`

**Comment by RobertAudi** [comment]
If you install the latest version of silicon you will get the new feature:

```console
$ cargo install --git https://github.com/Aloxaf/silicon
```

Maybe they are waiting for clipboard support on Windows for a new release 🤔 (See Aloxaf/silicon#3)

In any case I think this PR is not appropriate at this time, or at least it needs some work..

I suggest we either close it for now or add some kind of a label that says it's blocked or on hold.

**Comment by jaydorsey** [comment]
Version 0.3.0 (released in December) looks like it's added this functionality. The README still says Linux only for clipboard, but I ran the echo command above (after only doing a cargo install per your README) and it created the image and placed it on the clipboard.

My silicon version is 0.3.0

**Comment by segeljakt** [comment]
@jaydorsey could you give version 2 a try? #8 
```vim
Plug 'segeljakt/vim-silicon', { 'branch': 'version-2' }
```
It adds completions, clipboard support, and more. I have only tested it on my own machine so I am wondering if anyone else is experiencing problems.

**Comment by jaydorsey** [comment]
When I use the new branch, making a visual selection and doing `'<,'>Silicon foo` gives me a silicon success message and says it's copied to clipboard (which it indeed has)

The previous command, to echo, fails, however.

Also
- I can't do `Silicon foo` with a visual selection and have it save as a file now (it always copies to clipboard)
- `Silicon!` with a visual selection doesn't appear to do anything (no clipboard, and don't see a file saved). This is suggested in place of SiliconHighlight when I tried to run that (just to see)

Edit: I know you didn't ask to do the other 2 things, just noted because I was trying them to make sure that I had everything configured (on a diff computer than earlier, but same/similar setup and wanted to make sure I had things setup right). Please ignore if irrelevant. Thanks!

**Comment by RobertAudi** [comment]
I can see similar results to @jaydorsey on my setup, but I also tried the clipboard feature from the command-line using silicon and it did not work.
So it's either a problem with my config – I did not have enough time to confirm it – or it might be an issue with silicon itself (I tried the latest stable version from homebrew and the code from the master branch).

**Comment by segeljakt** [comment]
Ok, thank you for the reports, I will try to pin down the bugs

**Comment by jaydorsey** [comment]
@segeljakt  I mis-spoke about one of my results. I think I tried running `echo "ab" | silicon --to-clipboard --language python` as a vim command, not via CLI 🤦‍♂ 

silicon 0.3.0 built via `cargo install silicon` clipboard works just great. The other vim behaviors I noted still exist.

Thanks!

**Comment by segeljakt** [comment]
@jaydorsey @RobertAudi could you try now, for me these seem to work with the default configuration (`g:silicon` is not set to anything):
```vim
" Write to clipboard & default path
:Silicon            
:'<,'>Silicon
:'<,'>Silicon!

" Write to clipboard & specified path (foo)
:Silicon foo
:'<,'>Silicon foo
:'<,'>Silicon! foo
```
If you only want to write to the clipboard or a path, try:
```vim
" Write only to the default path
:Silicon --to-clipboard=false
" Write only to the the specified path (foo)
:Silicon --to-clipboard=false foo

" Alternatively you can set the option
let g:silicon = { 'to-clipboard': v:false }
:Silicon
:Silicon foo

" Write only to the clipboard
let g:silicon = { 'output': '' }
:Silicon
```

**Comment by RobertAudi** [comment]
@segeljakt I just tried again and it works! I used the `version-2` branch.

@jaydorsey If you confirm what I am saying I think I can close this pull request 🤔

**Comment by jaydorsey** [comment]
I just re-tested version-2 (macOS, nvim), including with the new options. Everything looks good to me and works as expected!

**Comment by RobertAudi** [comment]
Awesome. I'm closing this PR then.

**Comment by segeljakt** [comment]
@RobertAudi @jaydorsey thank you both so much for the help! 💯

**Pull request closed without merging**
